# Generated by Django 5.2.5 on 2025-08-15 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('word', models.CharField(db_column='word', max_length=255)),
                ('part_of_speech', models.CharField(db_column='part_of_speech', max_length=255)),
                ('level', models.CharField(db_column='level', max_length=255)),
                ('translation', models.CharField(blank=True, db_column='translation', max_length=255, null=True)),
                ('transcription', models.CharField(blank=True, db_column='transcription', max_length=255, null=True)),
                ('definition_examples', models.TextField(blank=True, db_column='definition_examples', null=True)),
            ],
            options={
                'db_table': 'words',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LearnedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='QuickCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quick_card', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
        ),
    ]
