# Generated by Django 5.2.5 on 2025-08-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('word_eng', models.CharField(db_column='word', max_length=255)),
                ('transcription', models.CharField(blank=True, db_column='transcription', max_length=255, null=True)),
                ('pos', models.CharField(db_column='pos', max_length=255)),
                ('translation', models.CharField(blank=True, db_column='translation', max_length=255, null=True)),
            ],
            options={
                'db_table': 'dict',
                'managed': False,
            },
        ),
    ]
